[package]
name = "artiq_streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
zmq = "0.10"
anyhow = "1"
tokio = {version = "1", features = ["full"]}
bytes = "1"
# combine = "4"
nom = "7"
colog = "1"
log = "0.4"
clap = {version = "4", features = ["derive"]}
